import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import styles from "./layout.module.scss";
import { ContextProvider } from "../providers/contextProvider";
import { QueryProvider } from "@/providers/queryProvider"
import { ReduxProvider } from "@/providers/reduxProvider";
import React, { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type IProps = {
  children: ReactNode;
}

const RootLayout: React.FC<IProps> = ({ children }) => {
  return (
    <QueryProvider>
      <ReduxProvider>
        <ContextProvider>
          <html lang="en">
            <body className={inter.className}>
              <div className={styles.wrapper}>
                <Header />
                {children}
              </div>
            </body>
          </html>
        </ContextProvider>
      </ReduxProvider>
    </QueryProvider>
  );
}

export default RootLayout